In [1]:
# JAI MAA SARASWATI

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [7]:
import numpy as np
list = [1,2,3,4,5]
array_list = np.array(list)

YES THERE IS THE DIFFERNCE IN THE BOTH DATA TYPES . 

* LIST IS THE STANDARD TYPES OF LIST IN THE PYTHON 

* ARRAY_LIST IS NUMPY ARRAY . 

let us printing the both list ^_^

In [10]:
list = [1,2,3,4,5]
array_list = np.array(list)
print(" DATA TYPE OF LIST:" , type(list))
print(" DATA TYPE OF ARRAY_LIST:" , type(array_list))

 DATA TYPE OF LIST: <class 'list'>
 DATA TYPE OF ARRAY_LIST: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [11]:
list = [1,2,3,4,5]
array_list = np.array(list)
 
# Print the data type of every element of the list :-
print(" Data type of element in list:")
for element in list:
    print(type(element))

# Print the Data type of every element in the array_list :-
print("\nData types of element in array_list:")
for element in array_list:
    print(type(array_list))

 Data type of element in list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of element in array_list:
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Yes there is difference between the list and array_list :-

* List => it is a standard list of the python and when we print the list it give the class list .
* array_list => It is a type of array_list of Numpy Library and when we print it then it gives the array data type

In [16]:
list = [1,2,3,4,5]
array_list = np.array(list , dtype = int)

# Print the element Data type present in the list:-
print(" Data type of the element in the list:")
for i in list:
    print(type(i))
    
# Print the element Data type present in the array_list:-
print(" Data type of the element in the array_list")
for ss in array_list:
    print(type(ss))

 Data type of the element in the list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
 Data type of the element in the array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
# Consider the below code to answer further questions:-
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i)	 shape
(ii) size

In [21]:
# Shape of the array_list:-
shape_of_array = np.shape(num_array)
print("Shape of the array_list:" , shape_of_array)

# Size of the array_list:-
size_of_array = np.size(num_array)
print("Size of the array_list:" , size_of_array)

Shape of the array_list: (2, 3)
Size of the array_list: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [25]:
# Create the 3x3 matrix with zeroes
zero_matrix = np.zeros((3,3))
print("Zero matrix with 3x3:")
print(zero_matrix)

Zero matrix with 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
# Create Identity matrix 5x5
identity_matrix = np.identity(5)
print("Identity matrix with 5x5:")
print(identity_matrix)

Identity matrix with 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
